name: Bug Report
description: Report a reproducible problem
title: "bug(scope): short description"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please describe the problem you're encountering.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the problem
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: false

  - type: input
    id: obsidian_version
    attributes:
      label: Obsidian Version
    validations:
      required: false

  - type: input
    id: plugin_version
    attributes:
      label: Plugin Version
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
