name: Feature Request
description: Suggest a new feature or improvement
title: "feat(scope): your idea"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Help us understand what you'd like to see added or changed.

  - type: textarea
    id: description
    attributes:
      label: Describe the Feature
      description: What would you like to happen?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem it Solves (optional)
      description: Is this solving a specific problem you’re facing?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions or workarounds have you tried?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
