name: Feature request
description: Suggest an idea to improve a project in The Silicate Society
title: "[Feature] <describe your request>"
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Describe the feature
      description: What would you like to see added or changed? Why is it useful?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case or motivation
      description: How would this improve your workflow or solve a problem?

  - type: textarea
    id: alternatives
    attributes:
      label: Have you considered other options?
      description: Are there any workarounds or related ideas you've explored?

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, references, or design suggestions welcome!
